<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\User;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create a test user
        $user = User::firstOrCreate(
            ['email' => 'seller@okbyowner.com'],
            [
                'name' => 'John Seller',
                'password' => bcrypt('password'),
                'role' => 'seller',
                'is_active' => true,
                'email_verified_at' => now(),
            ]
        );

        $properties = [
            [
                'user_id' => $user->id,
                'property_title' => 'Beautiful Family Home in Tulsa',
                'developer' => 'Simmons Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'price' => 299000,
                'address' => '1234 Oak Tree Lane',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74120',
                'subdivision' => 'Oak Hills',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'sqft' => 2500,
                'lot_size' => 8500,
                'year_built' => 2015,
                'description' => 'This stunning 4-bedroom home features an open floor plan, modern kitchen with granite countertops, hardwood floors throughout, and a spacious backyard perfect for entertaining. Located in a quiet neighborhood with easy access to schools and shopping.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Granite Countertops', 'Stainless Steel Appliances', 'Fenced Yard', 'Garage'],
                'photos' => ['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Modern Condo in Downtown OKC',
                'developer' => 'Clayco Development',
                'property_type' => 'condos-townhomes-co-ops',
                'status' => 'for-sale',
                'price' => 185000,
                'address' => '500 Main Street Unit 302',
                'city' => 'Oklahoma City',
                'state' => 'Oklahoma',
                'zip_code' => '73102',
                'subdivision' => 'Downtown District',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'sqft' => 1200,
                'lot_size' => null,
                'year_built' => 2018,
                'description' => 'Sleek modern condo in the heart of downtown Oklahoma City. Features floor-to-ceiling windows, contemporary finishes, and stunning city views. Building amenities include fitness center, rooftop deck, and secure parking.',
                'features' => ['Central AC', 'Central Heat', 'Walk-In Closet', 'Updated Kitchen', 'Security System', 'Balcony'],
                'photos' => ['https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Spacious Ranch in Norman',
                'developer' => 'Ideal Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'price' => 425000,
                'address' => '910 University Boulevard',
                'city' => 'Norman',
                'state' => 'Oklahoma',
                'zip_code' => '73019',
                'subdivision' => 'University Park',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'sqft' => 3200,
                'lot_size' => 12000,
                'year_built' => 2010,
                'description' => 'Expansive ranch-style home near the University of Oklahoma. Features include a chef\'s kitchen, formal dining room, home office, and finished basement. The large backyard includes a pool and covered patio.',
                'features' => ['Central AC', 'Central Heat', 'Swimming Pool', 'Covered Patio', 'Fireplace', 'Granite Countertops', 'Hardwood Floors', 'Garage', 'Sprinkler System'],
                'photos' => ['https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Charming Starter Home in Edmond',
                'developer' => 'Landmark Fine Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'price' => 275000,
                'address' => '2345 Covell Road',
                'city' => 'Edmond',
                'state' => 'Oklahoma',
                'zip_code' => '73034',
                'subdivision' => 'Covell Estates',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'sqft' => 1650,
                'lot_size' => 6500,
                'year_built' => 2012,
                'description' => 'Perfect starter home in the highly sought-after Edmond school district. Features an updated kitchen, new flooring, and a nice backyard. Move-in ready!',
                'features' => ['Central AC', 'Central Heat', 'Updated Kitchen', 'Fenced Yard', 'Garage', 'Carpet'],
                'photos' => ['https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Luxury Estate in Broken Arrow',
                'developer' => 'Shaw Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'price' => 650000,
                'address' => '8901 Aspen Creek Court',
                'city' => 'Broken Arrow',
                'state' => 'Oklahoma',
                'zip_code' => '74012',
                'subdivision' => 'Aspen Creek',
                'bedrooms' => 6,
                'bathrooms' => 5,
                'sqft' => 4500,
                'lot_size' => 18000,
                'year_built' => 2019,
                'description' => 'Stunning luxury estate with every amenity imaginable. Features include a gourmet kitchen, wine cellar, home theater, and resort-style backyard with pool and outdoor kitchen. Smart home technology throughout.',
                'features' => ['Central AC', 'Central Heat', 'Swimming Pool', 'Hot Tub', 'Fireplace', 'Granite Countertops', 'Hardwood Floors', 'Walk-In Closet', 'Security System', 'Sprinkler System', 'Covered Patio', 'Garage'],
                'photos' => ['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'is_featured' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Cozy Home in Lawton',
                'developer' => 'Homes by Taber',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'price' => 165000,
                'address' => '456 Cache Road',
                'city' => 'Lawton',
                'state' => 'Oklahoma',
                'zip_code' => '73505',
                'subdivision' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'sqft' => 1400,
                'lot_size' => 7000,
                'year_built' => 1998,
                'description' => 'Well-maintained home with recent updates including new roof, HVAC, and water heater. Great location near Fort Sill. Perfect for military families or first-time buyers.',
                'features' => ['Central AC', 'Central Heat', 'Fenced Yard', 'Garage', 'Updated Bathroom'],
                'photos' => ['https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Land for Development',
                'developer' => null,
                'property_type' => 'land',
                'status' => 'for-sale',
                'price' => 89000,
                'address' => 'Lot 15 Country Road',
                'city' => 'Moore',
                'state' => 'Oklahoma',
                'zip_code' => '73160',
                'subdivision' => null,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'sqft' => 0,
                'lot_size' => 43560,
                'year_built' => null,
                'description' => 'Beautiful 1-acre lot ready for your dream home. Utilities available at the street. Located in a growing area with easy highway access. No HOA restrictions.',
                'features' => ['Mature Trees'],
                'photos' => ['https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Multi-Family Investment Property',
                'developer' => 'Wallace Engineering',
                'property_type' => 'multi-family',
                'status' => 'for-sale',
                'price' => 385000,
                'address' => '1200 Rental Avenue',
                'city' => 'Stillwater',
                'state' => 'Oklahoma',
                'zip_code' => '74074',
                'subdivision' => null,
                'bedrooms' => 8,
                'bathrooms' => 4,
                'sqft' => 3600,
                'lot_size' => 10000,
                'year_built' => 2005,
                'description' => 'Excellent investment opportunity! 4-unit property near Oklahoma State University. All units currently rented with strong rental history. Each unit has 2 bedrooms and 1 bathroom.',
                'features' => ['Central AC', 'Central Heat', 'Garage'],
                'photos' => ['https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
            [
                'user_id' => $user->id,
                'property_title' => 'Historic Home in Midtown Tulsa',
                'developer' => 'McIntosh Construction',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'price' => 375000,
                'address' => '1821 S Boston Avenue',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74119',
                'subdivision' => 'Midtown',
                'bedrooms' => 4,
                'bathrooms' => 2.5,
                'sqft' => 2800,
                'lot_size' => 9000,
                'year_built' => 1925,
                'description' => 'Beautifully restored 1920s craftsman home in historic Midtown Tulsa. Original hardwood floors, built-in cabinetry, and period details throughout. Updated kitchen and bathrooms while maintaining historic charm.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Fireplace', 'Covered Patio', 'Mature Trees', 'Garage'],
                'photos' => ['https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800'],
                'contact_name' => 'John Seller',
                'contact_email' => 'seller@okbyowner.com',
                'contact_phone' => '(918) 555-0123',
                'is_active' => true,
                'is_featured' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
            ],
        ];

        foreach ($properties as $propertyData) {
            Property::create($propertyData);
        }

        $this->command->info('Created ' . count($properties) . ' sample properties!');
    }
}
